name: jeroenriemsdijk
favicon: null
layout_spectrum: 0.87928
typography_spectrum: 0.949939637677744
title: Homepage
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3945339173078537
  lightness: 0.5344008207321167
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
